### ISSUE TITLE
Binary op for SLong and SInt fails to build

### ISSUE THREAD

**Issue by oskin1** [ScorexFoundation/sigmastate-interpreter#320]
```
  property("Binary op (SLong, SInt)") {
    DefaultSigmaBuilder.mkPlus(ExtractRegisterAs[SLong.type](Self, R4).get, 100) shouldBe
      ArithOp(OptionGet(ExtractRegisterAs(Self, org.ergoplatform.ErgoBox.R4)), ConstantNode[SLong.type](100, SLong), -102: Byte)
  }
```
Fails with:
```
An exception or error caused a run to abort: Failed constraint sigmastate.lang.Constraints$$$Lambda$210/880533231@253c1256 for binary operation parameters (OptionGet(ExtractRegisterAs(Self,org.ergoplatform.ErgoBox$R4$@67fe380b,Option[SLong]))(tpe: SLong), ConstantNode(0,SInt)(tpe: SInt)) 
sigmastate.lang.exceptions.ConstraintFailed: Failed constraint sigmastate.lang.Constraints$$$Lambda$210/880533231@253c1256 for binary operation parameters (OptionGet(ExtractRegisterAs(Self,org.ergoplatform.ErgoBox$R4$@67fe380b,Option[SLong]))(tpe: SLong), ConstantNode(0,SInt)(tpe: SInt))
	at sigmastate.lang.TypeConstraintCheck.$anonfun$check2$1(SigmaBuilder.scala:450)
	at sigmastate.lang.TypeConstraintCheck.$anonfun$check2$1$adapted(SigmaBuilder.scala:448)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at sigmastate.lang.TypeConstraintCheck.check2(SigmaBuilder.scala:448)
	at sigmastate.lang.TypeConstraintCheck.check2$(SigmaBuilder.scala:445)
	at sigmastate.lang.DefaultSigmaBuilder$.check2(SigmaBuilder.scala:520)
	at sigmastate.lang.CheckingSigmaBuilder.arithOp(SigmaBuilder.scala:511)
	at sigmastate.lang.CheckingSigmaBuilder.arithOp$(SigmaBuilder.scala:508)
	at sigmastate.lang.DefaultSigmaBuilder$.arithOp(SigmaBuilder.scala:520)
	at sigmastate.lang.StdSigmaBuilder.mkPlus(SigmaBuilder.scala:198)
	at sigmastate.package$.Plus(sigmastate.scala:11)
	at org.ergoplatform.nodeView.state.ErgoState$.rewardOutputScript(ErgoState.scala:170)
	at org.ergoplatform.nodeView.state.ErgoState$.feeProposition(ErgoState.scala:180)
	at org.ergoplatform.utils.ErgoTestConstants.$init$(ErgoTestConstants.scala:32)
	at org.ergoplatform.mining.ErgoMinerPropSpec.<init>(ErgoMinerPropSpec.scala:12)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:560)
	at org.scalatest.tools.Runner$.genSuiteConfig(Runner.scala:1431)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$8(Runner.scala:1239)
	at scala.collection.immutable.List.map(List.scala:282)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1238)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1033)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1011)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1509)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1011)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

**Comment by oskin1** [comment]
Turned out to be not a bug but feature.
