### ISSUE TITLE
Serialization fails for Soption.map and SOption.filter

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#422]
Currently ignored tests SOption.map and SOption.filter are failing due to serialization roundtrip, the error is following:

sigmastate.lang.Terms$Lambda cannot be cast to sigmastate.Values$Constant
java.lang.ClassCastException: sigmastate.lang.Terms$Lambda cannot be cast to sigmastate.Values$Constant
	at sigmastate.serialization.ConstantSerializer.serialize(ConstantSerializer.scala:12)
	at sigmastate.serialization.ValueSerializer$.serialize(ValueSerializer.scala:172)
	at sigmastate.utils.SigmaByteWriter.putValue(SigmaByteWriter.scala:58)
	at sigmastate.utils.SigmaByteWriter.$anonfun$putValues$1(SigmaByteWriter.scala:61)

**Comment by greenhat** [comment]
Fixed in #469
