### ISSUE TITLE
Finish BinXor implementation

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#424]
Currently ignored "BinXor(logical XOR) equivalence" is failing due to the following error:

sigmastate.lang.exceptions.CosterException: Cannot find BinOp for opcode -12
	at sigmastate.eval.RuntimeCosting.error(RuntimeCosting.scala:1865)
	at sigmastate.eval.RuntimeCosting.error$(RuntimeCosting.scala:1865)
	at sigmastate.helpers.SigmaTestingCommons$TestingIRContext.error(SigmaTestingCommons.scala:91)
	at sigmastate.eval.RuntimeCosting.opcodeToBinOp(RuntimeCosting.scala:1022)
	at sigmastate.eval.RuntimeCosting.opcodeToBinOp$(RuntimeCosting.scala:1015)
	at sigmastate.helpers.SigmaTestingCommons$TestingIRContext.opcodeToBinOp(SigmaTestingCommons.scala:91)
	at sigmastate.eval.RuntimeCosting.evalNode(RuntimeCosting.scala:1686)
	at sigmastate.eval.RuntimeCosting.evalNode$(RuntimeCosting.scala:1111)

**Comment by gostkin** [comment]
https://github.com/ScorexFoundation/sigmastate-interpreter/pull/478
