### ISSUE TITLE
For Option type, .map and .filter do not work

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#425]
In addition to #422 , "Option.map" and "Option.filter" tests in BasicOpsSpecification are failing with the following error:

key not found: T
java.util.NoSuchElementException: key not found: T
	at scala.collection.immutable.ListMap$Node.applyInternal(ListMap.scala:129)
	at scala.collection.immutable.ListMap$Node.apply(ListMap.scala:126)
	at special.collection.impl.CostsDefs$CostedOption$CostedOptionAdapter.eT$lzycompute(CostsImpl.scala:1276)
	at special.collection.impl.CostsDefs$CostedOption$CostedOptionAdapter.eT(CostsImpl.scala:1276)
	at special.collection.impl.CostsDefs$CostedOption$CostedOptionAdapter.<init>(CostsImpl.scala:1278)
	at special.collection.impl.CostsDefs$CostedOption$.proxyCostedOption(CostsImpl.scala:1374)
	at sigmastate.eval.RuntimeCosting.evalNode(RuntimeCosting.scala:1271)
	at sigmastate.eval.RuntimeCosting.evalNode$(RuntimeCosting.scala:1111)

**Comment by greenhat** [comment]
Fixed in #469
