### ISSUE TITLE
Don't know how to compute Sized for type StringType

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/sigmastate-interpreter#432]
Sometimes Ergo tests fail with ` java.lang.RuntimeException: Don't know how to compute Sized for type StringType`. 
Occured once in out travis (https://travis-ci.org/ergoplatform/ergo/builds/505129353#L789)
```
[info] - Generate asset issuing transaction *** FAILED ***
[info]   java.lang.Exception: Failed to sign boxes: Vector(ErgoBox(f3f1ff020865ced128e5b61aad2a3afce111cf9a09bf4d6ab49f6839d51bc28e,67500000000,ErgoTree(16,WrappedArray(IntConstant(-1000), ConstantNode(ProveDlog((26df75ea615c18acc6bb4b517ac82795872f388d5d180aac90eaa84de750b942,42d8db59293536df222cc28aabd40e34a64297c2704c611cf60e35d63b297d21,1)),SSigmaProp)),SigmaAnd(WrappedArray(BoolToSigmaProp(GE(Height,Plus(SelectField(ExtractCreationInfo(Self),1), ConstantPlaceholder(0,SInt)))), ConstantPlaceholder(1,SSigmaProp))),SigmaAnd(ArrayBuffer(BoolToSigmaProp(GE(Height,Plus(SelectField(ExtractCreationInfo(Self),1), IntConstant(-1000)))), ConstantNode(ProveDlog((26df75ea615c18acc6bb4b517ac82795872f388d5d180aac90eaa84de750b942,42d8db59293536df222cc28aabd40e34a64297c2704c611cf60e35d63b297d21,1)),SSigmaProp)))),tokens: (List()), d8ae69e006eb5bfc45496a5d07789d117a0b6ec02fdc996d554b7dacc31997ef, 1, Map(), 1))
[info]   at org.ergoplatform.nodeView.wallet.ErgoWalletActor.$anonfun$generateTransactionWithOutputs$22(ErgoWalletActor.scala:232)
[info]   at scala.util.Failure.fold(Try.scala:240)
[info]   at org.ergoplatform.nodeView.wallet.ErgoWalletActor.$anonfun$generateTransactionWithOutputs$17(ErgoWalletActor.scala:232)
[info]   at scala.Option.map(Option.scala:163)
[info]   at org.ergoplatform.nodeView.wallet.ErgoWalletActor.$anonfun$generateTransactionWithOutputs$1(ErgoWalletActor.scala:215)
[info]   at scala.util.Success.flatMap(Try.scala:251)
[info]   at org.ergoplatform.nodeView.wallet.ErgoWalletActor.org$ergoplatform$nodeView$wallet$ErgoWalletActor$$generateTransactionWithOutputs(ErgoWalletActor.scala:192)
[info]   at org.ergoplatform.nodeView.wallet.ErgoWalletActor$$anonfun$receive$1.applyOrElse(ErgoWalletActor.scala:286)
[info]   at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
[info]   at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
[info]   ...
[info]   Cause: java.lang.RuntimeException: Don't know how to compute Sized for type StringType
[info]   at scala.sys.package$.error(package.scala:30)
[info]   at sigmastate.eval.Sized$.typeToSized(Sized.scala:60)
[info]   at sigmastate.eval.Sized$.$anonfun$anyValueIsSized$1(Sized.scala:69)
[info]   at sigmastate.eval.Sized$.sizeOf(Sized.scala:22)
[info]   at sigmastate.eval.Sized$.sizeOfAnyValue(Sized.scala:81)
[info]   at sigmastate.eval.Sized$.$anonfun$sizeOfRegisters$1(Sized.scala:86)
[info]   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[info]   at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
[info]   at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
[info]   at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
```

**Comment by catena2w** [comment]
Reproducing test: https://github.com/ergoplatform/ergo/pull/643/commits/30d94d87af113309e355350582606965c16e4165

**Comment by aslesarenko** [comment]
String type is not suppoted as register value.
