### ISSUE TITLE
OOM exception in the runtime costing

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#687]
One of the testnet nodes is failing often with:

java.lang.OutOfMemoryError: Java heap space
	at debox.Set$.ofAllocatedSize$mIc$sp(Set.scala:815)
	at debox.Set$mcI$sp.grow$mcI$sp(Set.scala:366)
	at debox.Set$mcI$sp.loop$14(Set.scala:213)
	at debox.Set$mcI$sp.$plus$eq$mcI$sp(Set.scala:219)
	at sigmastate.eval.RuntimeCosting.createDefinition(RuntimeCosting.scala:1094)
	at sigmastate.eval.RuntimeCosting.createDefinition$(RuntimeCosting.scala:1085)
	at sigmastate.eval.RuntimeIRContext.createDefinition(IRContext.scala:150)
	at scalan.Base.findOrCreateDefinition(Base.scala:774)
	at scalan.Base.toExp(Base.scala:806)
	at scalan.Base.reifyObject(Base.scala:577)
	at scalan.primitives.UniversalOps.opCost(UniversalOps.scala:53)
	at scalan.primitives.UniversalOps.opCost$(UniversalOps.scala:50)
	at scalan.Scalan.opCost(Scalan.scala:20)
	at sigmastate.eval.RuntimeCosting.evalNode(RuntimeCosting.scala:1599)
	at sigmastate.eval.RuntimeCosting.evalNode$(RuntimeCosting.scala:1149)
	at sigmastate.eval.RuntimeIRContext.evalNode(IRContext.scala:150)
	at sigmastate.eval.RuntimeCosting.sigmastate$eval$RuntimeCosting$$eval$1(RuntimeCosting.scala:1151)
	at sigmastate.eval.RuntimeCosting.evalNode(RuntimeCosting.scala:1728)
	at sigmastate.eval.RuntimeCosting.evalNode$(RuntimeCosting.scala:1149)
	at sigmastate.eval.RuntimeIRContext.evalNode(IRContext.scala:150)
	at sigmastate.eval.RuntimeCosting.sigmastate$eval$RuntimeCosting$$eval$1(RuntimeCosting.scala:1151)
	at sigmastate.eval.RuntimeCosting.evalNode(RuntimeCosting.scala:1548)
	at sigmastate.eval.RuntimeCosting.evalNode$(RuntimeCosting.scala:1149)
	at sigmastate.eval.RuntimeIRContext.evalNode(IRContext.scala:150)
	at sigmastate.eval.RuntimeCosting.sigmastate$eval$RuntimeCosting$$eval$1(RuntimeCosting.scala:1151)
	at sigmastate.eval.RuntimeCosting.$anonfun$evalNode$23(RuntimeCosting.scala:1702)
	at sigmastate.eval.RuntimeCosting$$Lambda$2398/1164684836.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.TraversableLike$$Lambda$11/1138193439.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)

**Comment by aslesarenko** [comment]
Hard to tell anything based on this stack trace alone. 
Would be useful to know the ErgoTree and the context data.
Most probably it is a Ergo node configuration problem or maybe OS memory is limited somehow.

**Comment by kushti** [comment]
@aslesarenko enough memory is given definitely, I can provide you access to the machine

**Comment by aslesarenko** [comment]
Nothing to be done on Sigma side.
