### ISSUE TITLE
Possible NullPointerException during evaluation 

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#778]
Got an error on one of the nodes:

09:26:30.678 WARN  [tor.default-dispatcher-14] o.e.n.state.UtxoState - Error while applying full block with header 2fbcd449a97d11cab4d2fcf4405481d5257a0110661f5a320f9e0849418bbc7a to UTXOState with root 9d0f3559bdd1fe7dbc36a0a933a8ff9e2e78c6d110cd4f92a5aa036fd8a2c17a18, reason: scorex.core.validation.MalformedModifierError: Scripts of all transaction inputs should pass verification. ee729d6cc0e339b8ab34787b7655fca0e5eb881b84af7cc0c9d2456d4e05f6e5: #1 => Failure(java.lang.NullPointerException) 

For this block: https://explorer.ergoplatform.com/en/blocks/2fbcd449a97d11cab4d2fcf4405481d5257a0110661f5a320f9e0849418bbc7a

**Comment by aslesarenko** [comment]
@kushti any chance of getting full stack for such errors? 
It is impossible to chase the root cause without it.
Which release is used on that node?

**Comment by kushti** [comment]
> @kushti any chance of getting full stack for such errors? It is impossible to chase the root cause without it. Which release is used on that node?

Latest 4.0.23 candidate, log got cleared on restart, unfortunately

**Comment by kushti** [comment]
More info 

```
20:26:55.620 WARN  [tor.default-dispatcher-12] o.e.m.m.ErgoTransaction - Tx 0b558aaddedcc2ee58206085c9e3c38ae549721e77764f6f9f10cefb5af723a4 verification failed: null : 
java.lang.NullPointerException: null
	at scalan.Base.createDefinition(Base.scala:795)
	at sigmastate.eval.RuntimeIRContext.sigmastate$eval$RuntimeCosting$$super$createDefinition(IRContext.scala:145)
	at sigmastate.eval.RuntimeCosting.createDefinition(RuntimeCosting.scala:1046)
	at sigmastate.eval.RuntimeCosting.createDefinition$(RuntimeCosting.scala:1045)
	at sigmastate.eval.RuntimeIRContext.createDefinition(IRContext.scala:145)
	at scalan.Base.findOrCreateDefinition(Base.scala:782)
	at scalan.Base.toExp(Base.scala:814)
	at scalan.Base.reifyObject(Base.scala:585)
	at scalan.Library.$anonfun$_specialPredef$1(Library.scala:41)
	at scalan.MutableLazy.value(MutableLazy.scala:13)
	at scalan.Library.specialPredef(Library.scala:42)
	at scalan.Library.specialPredef$(Library.scala:42)
	at sigmastate.eval.RuntimeIRContext.specialPredef(IRContext.scala:145)
	at sigmastate.eval.Evaluation.getDataEnv(Evaluation.scala:333)
	at sigmastate.eval.Evaluation.getDataEnv$(Evaluation.scala:331)
	at sigmastate.eval.RuntimeIRContext.getDataEnv(IRContext.scala:145)
	at sigmastate.eval.IRContext.$anonfun$checkCostWithContext$1(IRContext.scala:129)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.eval.IRContext.checkCostWithContext(IRContext.scala:127)
	at sigmastate.eval.IRContext.checkCostWithContext$(IRContext.scala:126)
	at sigmastate.eval.RuntimeIRContext.checkCostWithContext(IRContext.scala:145)
	at sigmastate.interpreter.PrecompiledScriptReducer.$anonfun$reduce$2(PrecompiledScriptProcessor.scala:84)
	at org.ergoplatform.validation.ValidationRules$.trySoftForkable(ValidationRules.scala:375)
```

context: 

```
Tx 0b558aaddedcc2ee58206085c9e3c38ae549721e77764f6f9f10cefb5af723a4 verification context: {
  "lastBlockUtxoRoot" : {
    "digest" : "23299083ae0e9bfcfa0f0fc82d5d8f71a2b147b582606d2c3c430ba7e8886b2d18",
    "treeFlags" : 7,
    "keyLength" : 32,
    "valueLength" : null
  },
  "headers" : [
    {
      "powOnetimePk" : "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
      "extensionRoot" : "131b840eb920b27e5e66b49302b54616f9bc052e669ca2cfc697c7ab9bfd5ab6",
      "votes" : "000000",
      "timestamp" : 1650306238151,
      "stateRoot" : {
        "digest" : "23299083ae0e9bfcfa0f0fc82d5d8f71a2b147b582606d2c3c430ba7e8886b2d18",
        "treeFlags" : 7,
        "keyLength" : 32,
        "valueLength" : null
      },
      "powDistance" : 0,
      "height" : 730996,
      "nBits" : 117852870,
      "version" : 2,
      "id" : "95cc408b2fec948c44a1638f69cfa982e1bd906ed39531ba68d357727bf2ea80",
      "minerPk" : "02ebaaeb381c9d855af1807781fa20ef6c0c34833275ce7913a9e4469f7bcb3bec",
      "adProofsRoot" : "7fa4acdbbc7f1c7d3f8046b31aee1cb598cfd6401ac168c6be90ae3f157e8be6",
--
    }
  ],
  "spendingTransaction" : {
    "id" : "0b558aaddedcc2ee58206085c9e3c38ae549721e77764f6f9f10cefb5af723a4",
    "inputs" : [
      {
        "boxId" : "4f15efd746e92edff6616861c53e1637883b80abd4d2778ce4b65f2431fc5b98",
        "spendingProof" : {
          "proofBytes" : "",
          "extension" : {
            
          }
        }
      },
      {
        "boxId" : "46d30293a5655fd1017b4eb2fe8b75864abf91cbe8fdd3035904c307cc329a9f",
        "spendingProof" : {
          "proofBytes" : "",
          "extension" : {
            
          }
        }
      }
    ],
    "dataInputs" : [
    ],
    "outputs" : [
      {
        "boxId" : "805eb3d9e44cdc5bd304600834012c96762b3a46d7973f2e17f8b5b2f0c7bd08",
--
        "additionalRegisters" : {
          "R4" : "04c60f"
        },
        "transactionId" : "0b558aaddedcc2ee58206085c9e3c38ae549721e77764f6f9f10cefb5af723a4",
        "index" : 0
      },
      {
        "boxId" : "8179f497a283e05e1a77fbae0179e772d4bc4b650d9a0ee0553d0796d48bb3d5",
        "value" : 420183440,
        "ergoTree" : "0008cd02541d14097cdb1d512e2cc6241b7fb913ee95a019f36e2a048809cd359240aee4",
        "assets" : [
        ],
        "creationHeight" : 0,
        "additionalRegisters" : {
          
        },
        "transactionId" : "0b558aaddedcc2ee58206085c9e3c38ae549721e77764f6f9f10cefb5af723a4",
        "index" : 1
      },
      {
        "boxId" : "80688107faac6719774d24ccb4f68b6416e343e2f435be65fd6374ed55d1591c",
        "value" : 4059931,
        "ergoTree" : "0008cd0273cbc003da723c0a5f416929692e8ec8c2b1e0d9aed69ff681f7581c63e70309",
        "assets" : [
        ],
        "creationHeight" : 0,
        "additionalRegisters" : {
          
        },
        "transactionId" : "0b558aaddedcc2ee58206085c9e3c38ae549721e77764f6f9f10cefb5af723a4",
        "index" : 2
      },
      {
        "boxId" : "369b4a2a9f1196df8f6f81a040fe5e9bbe4009fdbb27e4ba5fb4c6ba7c9bdced",
        "value" : 2000000,
        "ergoTree" : "1005040004000e36100204a00b08cd0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798ea02d192a39a8cc7a701730073011001020402d19683030193a38cc7b2a57300000193c2b2a57301007473027303830108cdeeac93b1a57304",
        "assets" : [
        ],
        "creationHeight" : 0,
        "additionalRegisters" : {
          
        },
        "transactionId" : "0b558aaddedcc2ee58206085c9e3c38ae549721e77764f6f9f10cefb5af723a4",
        "index" : 3
      }
    ]
  },
  "selfIndex" : 1,
  "extension" : {
    
  },
  "validationSettings" : "10e8070001e9070001ea070001eb070001ec070001ed070001ee070001ef070001f0070001f1070001f2070001f3070001f4070001f5070001f6070001f7070001",
  "costLimit" : 4946678,
  "initCost" : 0,
  "scriptVersion" : 1
} input context: InputContext(1,ContextExtension(Map())) proof: ProverResult(,ContextExtension(Map()))messageToSign: [B@36a46c27
20:26:55.622 WARN  [ctor.default-dispatcher-4] o.e.m.m.ErgoTransaction - Tx 0cf0d4e58f581b8dafbea74007fae75d6a38bee49d53db11db15633fd277edf8 verification context: {
  "lastBlockUtxoRoot" : {
    "digest" : "23299083ae0e9bfcfa0f0fc82d5d8f71a2b147b582606d2c3c430ba7e8886b2d18",
    "treeFlags" : 7,
    "keyLength" : 32,
    "valueLength" : null
  },
  "headers" : [
    {
      "powOnetimePk" : "0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798",
      "extensionRoot" : "131b840eb920b27e5e66b49302b54616f9bc052e669ca2cfc697c7ab9bfd5ab6",
      "votes" : "000000",
--
  "initCost" : 0,
  "scriptVersion" : 1
} 
input context: InputContext(1,ContextExtension(Map())) proof: ProverResult(,ContextExtension(Map()))messageToSign: [B@597a58e8
```

**Comment by kushti** [comment]
Looking for all errors: 

```
20:51:37.856 WARN  [tor.default-dispatcher-12] o.e.m.m.ErgoTransaction - Tx b8153beccbbe74007152de604b2e3d1d69a094677c88d40851832eef8c04b242 verification failed: assertion failed : 
20:51:37.856 WARN  [ctor.default-dispatcher-4] o.e.m.m.ErgoTransaction - Tx 86bb673c35d0cfb6ad54675d67758c4618e1b852f784939bb120c1c8bcbbb8a3 verification failed: null : 
20:51:37.856 WARN  [tor.default-dispatcher-13] o.e.m.m.ErgoTransaction - Tx 41fc07974da4599b2d47cc9c6795dcc77c9eb29fc9a2dbe845cbf7bf25359fae verification failed: null : 
20:51:37.856 WARN  [ctor.default-dispatcher-5] o.e.m.m.ErgoTransaction - Tx 41fc07974da4599b2d47cc9c6795dcc77c9eb29fc9a2dbe845cbf7bf25359fae verification failed: null : 
20:51:37.864 WARN  [tor.default-dispatcher-13] o.e.m.m.ErgoTransaction - Tx 86bb673c35d0cfb6ad54675d67758c4618e1b852f784939bb120c1c8bcbbb8a3 verification failed: null : 
20:51:37.869 WARN  [tor.default-dispatcher-13] o.e.m.m.ErgoTransaction - Tx b8153beccbbe74007152de604b2e3d1d69a094677c88d40851832eef8c04b242 verification failed: null : 
20:51:37.884 WARN  [tor.default-dispatcher-10] o.e.m.m.ErgoTransaction - Tx 0132b36d609bdd742e80d07ac8b178a3cc3287db1a560649424a9bdbc1ca844e verification failed: null : 
20:54:30.414 WARN  [tor.default-dispatcher-11] o.e.m.m.ErgoTransaction - Tx 86bb673c35d0cfb6ad54675d67758c4618e1b852f784939bb120c1c8bcbbb8a3 verification failed: null : 
```


*assertion failed* from above has following details:

```
20:51:37.856 WARN  [tor.default-dispatcher-12] o.e.m.m.ErgoTransaction - Tx b8153beccbbe74007152de604b2e3d1d69a094677c88d40851832eef8c04b242 verification failed: assertion failed : 
java.lang.AssertionError: assertion failed
	at scala.Predef$.assert(Predef.scala:208)
	at scalan.Base.updateSymbolTable(Base.scala:712)
	at scalan.Base.freshSym(Base.scala:681)
	at scalan.Base$Def.self(Base.scala:164)
	at scalan.Base$Def.self$(Base.scala:163)
	at scalan.Base$CompanionDef.self(Base.scala:212)
	at scalan.Base.$anonfun$reifyObject$1(Base.scala:585)
	at scalan.Base.findOrCreateDefinition(Base.scala:782)
	at scalan.Base.toExp(Base.scala:814)
	at scalan.Base.reifyObject(Base.scala:585)
	at scalan.Library.$anonfun$_specialPredef$1(Library.scala:41)
	at scalan.MutableLazy.value(MutableLazy.scala:13)
	at scalan.Library.specialPredef(Library.scala:42)
	at scalan.Library.specialPredef$(Library.scala:42)
	at sigmastate.eval.RuntimeIRContext.specialPredef(IRContext.scala:145)
	at sigmastate.eval.Evaluation.getDataEnv(Evaluation.scala:333)
	at sigmastate.eval.Evaluation.getDataEnv$(Evaluation.scala:331)
	at sigmastate.eval.RuntimeIRContext.getDataEnv(IRContext.scala:145)
	at sigmastate.eval.IRContext.$anonfun$checkCostWithContext$1(IRContext.scala:129)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.eval.IRContext.checkCostWithContext(IRContext.scala:127)
	at sigmastate.eval.IRContext.checkCostWithContext$(IRContext.scala:126)
	at sigmastate.eval.RuntimeIRContext.checkCostWithContext(IRContext.scala:145)
	at sigmastate.interpreter.PrecompiledScriptReducer.$anonfun$reduce$2(PrecompiledScriptProcessor.scala:84)
	at org.ergoplatform.validation.ValidationRules$.trySoftForkable(ValidationRules.scala:375)
	at sigmastate.interpreter.PrecompiledScriptReducer.reduce(PrecompiledScriptProcessor.scala:81)
	at sigmastate.interpreter.Interpreter.fullReduction(Interpreter.scala:186)
	at sigmastate.interpreter.Interpreter.fullReduction$(Interpreter.scala:174)
	at org.ergoplatform.ErgoLikeInterpreter.fullReduction(ErgoLikeInterpreter.scala:14)
	at sigmastate.interpreter.Interpreter.$anonfun$verify$2(Interpreter.scala:256)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.interpreter.Interpreter.$anonfun$verify$1(Interpreter.scala:230)
	at scalan.util.BenchmarkUtil$.measureTime(BenchmarkUtil.scala:29)
	at sigmastate.interpreter.Interpreter.verify(Interpreter.scala:230)
```


So I guess the issue is in multi-thread access to *_symbolTable* in Base, thus PrecompiledScriptProcessor is not thread-safe probably (in opposite to what its ScalaDoc says)
