### ISSUE TITLE
5cc37727ae461bc36045a5d6cc3d12b0ac4ecf5935b7ee940716237f25fb6cee validation 

### ISSUE THREAD

**Issue by kushti** [ScorexFoundation/sigmastate-interpreter#784]
Tx 5cc37727ae461bc36045a5d6cc3d12b0ac4ecf5935b7ee940716237f25fb6cee was included into blocks , but verification failed for some time, then successful block appeared https://explorer.ergoplatform.com/en/transactions/5cc37727ae461bc36045a5d6cc3d12b0ac4ecf5935b7ee940716237f25fb6cee . 

Example of error message: 

18:12:46.898 WARN  [tor.default-dispatcher-12] o.e.m.m.ErgoTransaction - Tx 5cc37727ae461bc36045a5d6cc3d12b0ac4ecf5935b7ee940716237f25fb6cee verification failed: Error in Evaluation.compile.evaluate(s4578 -> MethodCall(s4470, scalan.Base$Ref special.collection.Colls$Coll.foldLeft(scalan.Base$Ref,scalan.Base$Ref), [s4577, s1524], true)) : 
scalan.Base$StagingException: Error in Evaluation.compile.evaluate(s4578 -> MethodCall(s4470, scalan.Base$Ref special.collection.Colls$Coll.foldLeft(scalan.Base$Ref,scalan.Base$Ref), [s4577, s1524], true))
	at scalan.Base.$bang$bang$bang(Base.scala:38)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:750)
	at sigmastate.eval.Evaluation.$anonfun$compile$4(Evaluation.scala:666)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at sigmastate.eval.Evaluation.$anonfun$compile$3(Evaluation.scala:665)
	at sigmastate.eval.Evaluation.$anonfun$compile$7(Evaluation.scala:763)
	at sigmastate.eval.IRContext.$anonfun$checkCostWithContext$1(IRContext.scala:130)
	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.eval.IRContext.checkCostWithContext(IRContext.scala:127)
	at sigmastate.eval.IRContext.checkCostWithContext$(IRContext.scala:126)
	at sigmastate.eval.RuntimeIRContext.checkCostWithContext(IRContext.scala:145)
	at sigmastate.interpreter.PrecompiledScriptReducer.$anonfun$reduce$2(PrecompiledScriptProcessor.scala:84)
	at org.ergoplatform.validation.ValidationRules$.trySoftForkable(ValidationRules.scala:375)
	at sigmastate.interpreter.PrecompiledScriptReducer.reduce(PrecompiledScriptProcessor.scala:81)
	at sigmastate.interpreter.Interpreter.fullReduction(Interpreter.scala:186)
	at sigmastate.interpreter.Interpreter.fullReduction$(Interpreter.scala:174)
	at org.ergoplatform.ErgoLikeInterpreter.fullReduction(ErgoLikeInterpreter.scala:14)
	at sigmastate.interpreter.Interpreter.$anonfun$verify$2(Interpreter.scala:256)
	at scala.util.Try$.apply(Try.scala:213)
	at sigmastate.interpreter.Interpreter.$anonfun$verify$1(Interpreter.scala:230)
	at scalan.util.BenchmarkUtil$.measureTime(BenchmarkUtil.scala:29)
	at sigmastate.interpreter.Interpreter.verify(Interpreter.scala:230)
	at sigmastate.interpreter.Interpreter.verify$(Interpreter.scala:225)
	at org.ergoplatform.wallet.interpreter.ErgoInterpreter.verify(ErgoInterpreter.scala:81)
	at org.ergoplatform.wallet.interpreter.ErgoInterpreter.verify(ErgoInterpreter.scala:25)
	at sigmastate.interpreter.Interpreter.verify(Interpreter.scala:322)
	at sigmastate.interpreter.Interpreter.verify$(Interpreter.scala:317)
	at org.ergoplatform.ErgoLikeInterpreter.verify(ErgoLikeInterpreter.scala:14)
	at org.ergoplatform.modifiers.mempool.ErgoTransaction.$anonfun$validateStateful$42(ErgoTransaction.scala:218)
	at scorex.core.validation.ValidationState.$anonfun$validateSeq$2(ModifierValidator.scala:188)
	at scorex.core.validation.ValidationState.pass(ModifierValidator.scala:72)
	at scorex.core.validation.ValidationState.$anonfun$validateSeq$1(ModifierValidator.scala:188)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.ArrayBuffer.foldLeft(ArrayBuffer.scala:49)
	at scorex.core.validation.ValidationState.validateSeq(ModifierValidator.scala:187)
	at org.ergoplatform.modifiers.mempool.ErgoTransaction.validateStateful(ErgoTransaction.scala:205)
	at org.ergoplatform.nodeView.state.ErgoState$.$anonfun$execTransactions$12(ErgoState.scala:141)
	at scorex.core.validation.ValidationState.$anonfun$validateTry$2(ModifierValidator.scala:147)
	at scala.util.Success.fold(Try.scala:271)
	at scorex.core.validation.ValidationState.$anonfun$validateTry$1(ModifierValidator.scala:147)
	at scorex.core.validation.ValidationState.pass(ModifierValidator.scala:72)
	at scorex.core.validation.ValidationState.validateTry(ModifierValidator.scala:147)
	at org.ergoplatform.nodeView.state.ErgoState$.execTransactions(ErgoState.scala:140)
	at org.ergoplatform.nodeView.state.UtxoState.applyTransactions(UtxoState.scala:78)
	at org.ergoplatform.nodeView.state.UtxoState.$anonfun$applyModifier$1(UtxoState.scala:105)
	at scala.util.Success.flatMap(Try.scala:251)
	at org.ergoplatform.nodeView.state.UtxoState.applyModifier(UtxoState.scala:103)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.$anonfun$applyState$1(ErgoNodeViewHolder.scala:224)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:162)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:162)
	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:160)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.applyState(ErgoNodeViewHolder.scala:218)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.updateState(ErgoNodeViewHolder.scala:192)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.pmodModify(ErgoNodeViewHolder.scala:402)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder$$anonfun$processLocallyGeneratedModifiers$1.applyOrElse(ErgoNodeViewHolder.scala:563)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:175)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:176)
	at akka.actor.Actor.aroundReceive(Actor.scala:537)
	at akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.ergoplatform.nodeView.ErgoNodeViewHolder.aroundReceive(ErgoNodeViewHolder.scala:40)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: scalan.Base$StagingException: Cannot invoke method public abstract java.lang.Object special.collection.Coll.foldLeft(java.lang.Object,scala.Function1) on object Coll(sigmastate.eval.EvalSizeBox@4d6b7817,sigmastate.eval.EvalSizeBox@69bbf4b3,sigmastate.eval.EvalSizeBox@5d753b77,sigmastate.eval.EvalSizeBox@54afae3b,sigmastate.eval.EvalSizeBox@4292cf79,sigmastate.eval.EvalSizeBox@743aa5f4,sigmastate.eval.EvalSizeBox@608687,sigmastate.eval.EvalSizeBox@29973ec6,sigmastate.eval.EvalSizeBox@7d2ac58a,sigmastate.eval.EvalSizeBox@5c9ecade,sigmastate.eval.EvalSizeBox@584e2b74,sigmastate.eval.EvalSizeBox@483f5fb5,sigmastate.eval.EvalSizeBox@6392d5ad,sigmastate.eval.EvalSizeBox@49f02b3b,sigmastate.eval.EvalSizeBox@604cacfa,sigmastate.eval.EvalSizeBox@52bc95b1,sigmastate.eval.EvalSizeBox@27761df6,sigmastate.eval.EvalSizeBox@6f9753d0,sigmastate.eval.EvalSizeBox@6ab919a4,sigmastate.eval.EvalSizeBox@5c1e085f,sigmastate.eval.EvalSizeBox@4b903787,sigmastate.eval.EvalSizeBox@1ecce4f6,sigmastate.eval.EvalSizeBox@3c9aaab2,sigmastate.eval.EvalSizeBox@106a018e,sigmastate.eval.EvalSizeBox@5a8c300b,sigmastate.eval.EvalSizeBox@231e84f8,sigmastate.eval.EvalSizeBox@4a387513,sigmastate.eval.EvalSizeBox@a9e7bab,sigmastate.eval.EvalSizeBox@31a91e9b,sigmastate.eval.EvalSizeBox@66476512,sigmastate.eval.EvalSizeBox@6fde0424,sigmastate.eval.EvalSizeBox@16647957,sigmastate.eval.EvalSizeBox@6f40e0c6,sigmastate.eval.EvalSizeBox@32f277c9,sigmastate.eval.EvalSizeBox@2d12ba97,sigmastate.eval.EvalSizeBox@1889c0a3,sigmastate.eval.EvalSizeBox@70a745a4,sigmastate.eval.EvalSizeBox@51ca2846,sigmastate.eval.EvalSizeBox@6934f6ea,sigmastate.eval.EvalSizeBox@3f6ebfb7,sigmastate.eval.EvalSizeBox@752e579b,sigmastate.eval.EvalSizeBox@7526d960,sigmastate.eval.EvalSizeBox@3bebf288,sigmastate.eval.EvalSizeBox@71326145,sigmastate.eval.EvalSizeBox@76277277) with arguments WrappedArray((special.collection.CSizePrim@3589580a,10085), sigmastate.eval.Evaluation$$Lambda$2191/0x0000000840c98840@51928381)
	at scalan.Base.$bang$bang$bang(Base.scala:38)
	at scalan.TypeDescs$Elem.liftedTree2$1(TypeDescs.scala:218)
	at scalan.TypeDescs$Elem.invokeUnlifted(TypeDescs.scala:216)
	at scalan.TypeDescs.invokeUnlifted(TypeDescs.scala:295)
	at sigmastate.eval.RuntimeIRContext.scalan$Library$$super$invokeUnlifted(IRContext.scala:145)
	at scalan.Library.invokeUnlifted(Library.scala:166)
	at scalan.Library.invokeUnlifted$(Library.scala:160)
	at sigmastate.eval.RuntimeIRContext.invokeUnlifted(IRContext.scala:145)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:597)
	... 80 common frames omitted
Caused by: scalan.Base$StagingException: Error in Evaluation.compile.evaluate(s1537 -> OpCost(s1522, 122, WrappedArray(s1528), s1536))
	at scalan.Base.$bang$bang$bang(Base.scala:38)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:750)
	at sigmastate.eval.Evaluation.$anonfun$compile$4(Evaluation.scala:666)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
	at sigmastate.eval.Evaluation.$anonfun$compile$3(Evaluation.scala:665)
	at special.collection.CViewColl.$anonfun$foldLeft$1(ViewColls.scala:111)
	at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
	at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
	at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:198)
	at special.collection.CViewColl.foldLeft(ViewColls.scala:111)
	at jdk.internal.reflect.GeneratedMethodAccessor214.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at scalan.TypeDescs$Elem.liftedTree2$1(TypeDescs.scala:216)
	... 87 common frames omitted
Caused by: sigmastate.lang.exceptions.CostLimitException: Estimated execution cost 547875 exceeds the limit 544136
	at sigmastate.eval.Evaluation$CostAccumulator.add(Evaluation.scala:474)
	at sigmastate.eval.Evaluation.$anonfun$compile$1(Evaluation.scala:711)
	... 101 common frames omitted

Verification context: https://pastebin.com/Wwih1jsp

**Comment by kushti** [comment]
Fixed in 5.0
